services:
  app-dev:
    # สร้าง image จาก Dockerfile (โปรเจกต์นี้ไม่มี multi-stage จึงไม่สามารถกำหนด target แบบ builder ได้)
    build:
      context: .
    container_name: flask-app-dev-instance
    ports:
      - "5002:5000" # map port สำหรับ dev (host:container)
    volumes:
      # เชื่อมโค้ดจากเครื่องเราเข้าไปใน container แบบ Real-time เพื่อใช้ auto-reload ของ Flask
      - ./:/app
    environment:
      # เปิดโหมดพัฒนาและเปิด auto-reload
      FLASK_APP: app.py
      FLASK_DEBUG: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    # ติดตั้ง dependencies ทุกครั้งที่รัน (กันเคสแก้ requirements.txt แล้วไม่ rebuild image) และสั่งรัน flask dev server
    command: ["sh", "-c", "pip install --no-cache-dir -r requirements.txt && flask run --host=0.0.0.0 --port=5000"]
